import LegalPageLayout from '../components/LegalPageLayout'

// Public, unauthenticated route — see App.jsx and Privacy.jsx's file comment.
// No advertising/AdSense — considered, then dropped in favor of a different
// monetization path; keep this and Privacy.jsx in sync if that changes.
function Terms() {
	return (
		<LegalPageLayout title="Terms of Service" updated="August 17, 2026">
			<p>
				These terms cover your use of NoteMind. By creating an account you agree to them. If you
				don't agree, please don't use the app — and email us at{' '}
				<a href="mailto:notemind.ai.app@gmail.com">notemind.ai.app@gmail.com</a> if you have questions.
			</p>

			<h2>The service</h2>
			<p>
				NoteMind is free to use — there is no paid tier, subscription, or trial period today, and no
				advertising. If that ever changes for any part of the app, we'll say so clearly before it
				happens.
			</p>

			<h2>Your account</h2>
			<ul>
				<li>You must provide accurate information and keep your password confidential.</li>
				<li>You're responsible for activity that happens under your account.</li>
				<li>You must be at least 13 years old to use NoteMind.</li>
			</ul>

			<h2>Acceptable use</h2>
			<p>You agree not to:</p>
			<ul>
				<li>Use the app for anything illegal, or to store/share content you don't have the right to.</li>
				<li>Attempt to bypass rate limits, scrape, or abuse the AI features (Ask AI, auto-tagging, flashcards, etc.) to overload the service.</li>
				<li>Try to access another user's account or data, or interfere with the app's normal operation.</li>
			</ul>
			<p>We may suspend or terminate accounts that violate these terms.</p>

			<h2>Your content</h2>
			<p>
				You own what you write in NoteMind. We don't claim any ownership over your notes. By using
				an AI feature, you're asking us to send the relevant content to Google's Gemini API to
				generate that specific response — see our <a href="/privacy">Privacy Policy</a> for details.
			</p>

			<h2>AI features</h2>
			<p>
				Auto-tags, "Ask your notes" answers, suggested titles, flashcards, and the weekly digest are
				generated by AI and can be inaccurate or incomplete. Treat them as a starting point, not a
				source of truth — use your own judgment, especially for anything important.
			</p>

			<h2>Third-party services</h2>
			<p>
				Some features rely on third parties — Google Sign-In and Google Gemini. Your use of those
				features is also subject to Google's own terms.
			</p>

			<h2>Ending your account</h2>
			<p>
				You can delete your account at any time from the Account page — this is immediate and
				permanent. We may suspend or delete an account that violates these terms.
			</p>

			<h2>No warranty, limited liability</h2>
			<p>
				NoteMind is provided "as is," without warranties of any kind. We don't guarantee the service
				will be uninterrupted or error-free. We encourage you to export your notes regularly (JSON
				or Markdown, from the Account page) as your own backup. To the fullest extent permitted by
				law, we aren't liable for indirect, incidental, or consequential damages arising from your
				use of the app.
			</p>

			<h2>Changes to these terms</h2>
			<p>If we make a material change, we'll update the date at the top of this page.</p>

			<h2>Contact</h2>
			<p>Questions about these terms: <a href="mailto:notemind.ai.app@gmail.com">notemind.ai.app@gmail.com</a>.</p>
		</LegalPageLayout>
	)
}

export default Terms
